// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/MosaicRule":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../lang ../geometry/Point".split(" "),function(f,e,g,k,n,l){var c=f(null,{declaredClass:"esri.layers.MosaicRule",method:null,where:null,sortField:null,sortValue:null,ascending:!1,lockRasterIds:null,viewpoint:null,objectIds:null,operation:null,multidimensionalDefinition:[],constructor:function(h){e.isObject(h)&&(e.mixin(this,h),h.mosaicMethod&&(this.method=h.mosaicMethod),this.method&&
"esri"!==this.method.toLowerCase().substring(0,4)&&(this.method=this._getMethodEnum(this.method)),h.mosaicOperation&&(this.operation=h.mosaicOperation),this.operation&&"MT_"!==this.operation.toUpperCase().substring(0,3)&&(this.operation=this._getOperatorEnum(this.operation)),h.fids&&(this.objectIds=h.fids),h.viewpoint&&(this.viewpoint=new l(h.viewpoint)))},toJson:function(){var h=null,e=this.multidimensionalDefinition?this.multidimensionalDefinition.length:0;if(e)for(var h=[],c=0;c<e;c++)h.push("esri.layers.DimensionalDefinition"===
this.multidimensionalDefinition[c].declaredClass?this.multidimensionalDefinition[c].toJson():this.multidimensionalDefinition[c]);h={mosaicMethod:this.method,where:this.where,sortField:this.sortField,sortValue:this.sortValue,ascending:this.ascending,lockRasterIds:this.lockRasterIds,viewpoint:this.viewpoint?this.viewpoint.toJson():null,fids:this.objectIds,mosaicOperation:this.operation,multidimensionalDefinition:h};return n.filter(h,function(c){if(null!==c)return!0})},_getMethodEnum:function(e){if(e){var p=
c.METHOD_NONE;switch(e.toLowerCase()){case "byattribute":p=c.METHOD_ATTRIBUTE;break;case "center":p=c.METHOD_CENTER;break;case "lockraster":p=c.METHOD_LOCKRASTER;break;case "nadir":p=c.METHOD_NADIR;break;case "northwest":p=c.METHOD_NORTHWEST;break;case "seamline":p=c.METHOD_SEAMLINE;break;case "viewpoint":p=c.METHOD_VIEWPOINT}return p}},_getOperatorEnum:function(e){if(e)switch(e.toLowerCase()){case "first":return c.OPERATION_FIRST;case "last":return c.OPERATION_LAST;case "max":return c.OPERATION_MAX;
case "min":return c.OPERATION_MIN;case "blend":return c.OPERATION_BLEND;case "mean":return c.OPERATION_MEAN}}});e.mixin(c,{METHOD_NONE:"esriMosaicNone",METHOD_CENTER:"esriMosaicCenter",METHOD_NADIR:"esriMosaicNadir",METHOD_VIEWPOINT:"esriMosaicViewpoint",METHOD_ATTRIBUTE:"esriMosaicAttribute",METHOD_LOCKRASTER:"esriMosaicLockRaster",METHOD_NORTHWEST:"esriMosaicNorthwest",METHOD_SEAMLINE:"esriMosaicSeamline",OPERATION_FIRST:"MT_FIRST",OPERATION_LAST:"MT_LAST",OPERATION_MIN:"MT_MIN",OPERATION_MAX:"MT_MAX",
OPERATION_MEAN:"MT_MEAN",OPERATION_BLEND:"MT_BLEND"});g("extend-esri")&&e.setObject("layers.MosaicRule",c,k);return c})},"esri/tasks/ImageServiceIdentifyTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../request ../geometry/normalizeUtils ./Task ./ImageServiceIdentifyResult".split(" "),function(f,e,g,k,n,l,c,h){f=f(c,{declaredClass:"esri.tasks.ImageServiceIdentifyTask",constructor:function(c){this._url.path+="/identify";this._handler=e.hitch(this,this._handler)},__msigns:[{n:"execute",
c:3,a:[{i:0,p:["geometry"]}],e:2}],_handler:function(e,c,f,g,k){try{var n=new h(e);this._successHandler([n],"onComplete",f,k)}catch(l){this._errorHandler(l,g,k)}},execute:function(c,h,f,g){var k=g.assembly;c=this._encode(e.mixin({},this._url.query,{f:"json"},c.toJson(k&&k[0])));var l=this._handler,D=this._errorHandler;return n({url:this._url.path,content:c,callbackParamName:"callback",load:function(c,e){l(c,e,h,f,g.dfd)},error:function(c){D(c,f,g.dfd)}})},onComplete:function(){}});l._createWrappers(f);
g("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyTask",f,k);return f})},"esri/tasks/ImageServiceIdentifyResult":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../geometry/jsonUtils ./FeatureSet".split(" "),function(f,e,g,k,n,l){f=f(null,{declaredClass:"esri.tasks.ImageServiceIdentifyResult",constructor:function(c){c.catalogItems&&(this.catalogItems=new l(c.catalogItems));c.location&&(this.location=n.fromJson(c.location));this.catalogItemVisibilities=c.catalogItemVisibilities;
this.name=c.name;this.objectId=c.objectId;this.value=c.value;this.properties=c.properties}});g("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyResult",f,k);return f})},"esri/tasks/ImageServiceIdentifyParameters":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../lang ../geometry/jsonUtils".split(" "),function(f,e,g,k,n,l,c){f=f(null,{declaredClass:"esri.tasks.ImageServiceIdentifyParameters",geometry:null,mosaicRule:null,renderingRule:null,pixelSizeX:null,
pixelSizeY:null,pixelSize:null,returnGeometry:!1,returnCatalogItems:!0,timeExtent:null,toJson:function(e){var f=e&&e.geometry||this.geometry;e={geometry:f,returnGeometry:this.returnGeometry,returnCatalogItems:this.returnCatalogItems,mosaicRule:this.mosaicRule?g.toJson(this.mosaicRule.toJson()):null,renderingRule:this.renderingRule?g.toJson(this.renderingRule.toJson()):null};f&&(e.geometryType=c.getJsonType(f));f=this.timeExtent;e.time=f?f.toJson().join(","):null;l.isDefined(this.pixelSizeX)&&l.isDefined(this.pixelSizeY)?
e.pixelSize=g.toJson({x:parseFloat(this.pixelSizeX),y:parseFloat(this.pixelSizeY)}):this.pixelSize&&(e.pixelSize=this.pixelSize?g.toJson(this.pixelSize.toJson()):null);return e}});k("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyParameters",f,n);return f})},"*noref":1}});
define("esri/layers/ArcGISImageServiceLayer","dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/json dojo/_base/config dojo/has dojo/io-query ../kernel ../config ../lang ../request ../deferredUtils ../urlUtils ../geometry/Extent ../geometry/Point ../SpatialReference ./MosaicRule ./DynamicMapServiceLayer ./TimeInfo ./Field ../graphic ../tasks/ImageServiceIdentifyTask ../tasks/ImageServiceIdentifyParameters ../geometry/Polygon".split(" "),function(f,e,g,k,n,l,c,h,p,
G,C,u,r,F,D,I,Q,E,J,K,L,M,N,O,P){f=f(J,{declaredClass:"esri.layers.ArcGISImageServiceLayer",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0},constructor:function(a,d){this._url=F.urlToObject(a);var b=d&&d.imageServiceParameters;this.format=b&&b.format;this.interpolation=b?b.interpolation:null;this.compressionQuality=b?b.compressionQuality:null;this.bandIds=b?b.bandIds:null;this.mosaicRule=b?b.mosaicRule:null;this.renderingRule=b?b.renderingRule:null;this._params=e.mixin({},this._url.query,
{f:"image",interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},b?b.toJson():{});this._initLayer=e.hitch(this,this._initLayer);this._queryVisibleRastersHandler=e.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this.useMapImage=d&&d.useMapImage||!1;this.infoTemplate=d&&d.infoTemplate;this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._loadCallback=d&&d.loadCallback;
(b=d&&d.resourceInfo)?this._initLayer(b):u({url:this._url.path,content:e.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a,d){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();var b=this.minScale,c=this.maxScale;e.mixin(this,a);this.minScale=b;this.maxScale=c;this.initialExtent=this.fullExtent=this.extent=new D(a.extent);this.spatialReference=
this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);for(var f=this.minValues,h=this.maxValues,q=this.meanValues,g=this.stdvValues,k=this.bands=[],b=0,c=this.bandCount;b<c;b++)k[b]={min:f[b],max:h[b],mean:q[b],stddev:g[b]};this.timeInfo=(b=this.timeInfo)&&b.timeExtent?new K(b):null;c=this.fields=[];if(f=a.fields)for(b=0;b<f.length;b++)c.push(new L(f[b]));this.version=a.currentVersion;this.version||(this.version="fields"in a||"objectIdField"in
a||"timeInfo"in a?10:9.3);C.isDefined(a.minScale)&&!this._hasMin&&this.setMinScale(a.minScale);C.isDefined(a.maxScale)&&!this._hasMax&&this.setMaxScale(a.maxScale);b={};a.defaultMosaicMethod?(b.method=a.defaultMosaicMethod,b.operation=a.mosaicOperator,b.sortField=a.sortField,b.sortValue=a.sortValue):b.method=E.METHOD_NONE;this.defaultMosaicRule=new E(b);this.defaultMosaicRule.ascending=!0;10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(e.hitch(this,function(a){a&&
(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=e.clone(a.features));a&&(a.fields&&0<a.fields.length)&&(this._rasterAttributeTableFields=e.clone(a.fields))}));this.loaded=!0;this.onLoad(this);if(b=this._loadCallback)delete this._loadCallback,b(this)},getKeyProperties:function(){var a=this._url.path+"/keyProperties",d=new g(r._dfdCanceller);10<this.version?(d._pendingDfd=u({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),d._pendingDfd.then(function(a){d.callback(a)},
function(a){d.errback(a)})):(a=Error("Layer does not have key properties"),a.log=l.isDebug,d.errback(a));return d},getRasterAttributeTable:function(){var a=this._url.path+"/rasterAttributeTable",d=new g(r._dfdCanceller);10<this.version&&this.hasRasterAttributeTable?(d._pendingDfd=u({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),d._pendingDfd.then(function(a){d.callback(a)},function(a){d.errback(a)})):(a=Error("Layer does not support raster attribute table"),a.log=l.isDebug,
d.errback(a));return d},_getRasterAttributeTableFeatures:function(){var a=new g;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(e.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=e.clone(a.features))})),a;a.resolve(this._rasterAttributeTableFeatures);return a},getCustomRasterFields:function(a){var d=
a?a.rasterAttributeTableFieldPrefix:"",b={name:"Raster.ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};a=this.fields?e.clone(this.fields):[];var c=a.length;a[c]={name:"Raster.ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};if(this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")||this.fields&&0<this.fields.length)a[c+1]=b;this._rasterAttributeTableFields&&0<this._rasterAttributeTableFields.length&&
(b=k.filter(this._rasterAttributeTableFields,function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),b=k.map(b,function(a){var b=e.clone(a);b.name=d+a.name;return b}),a=a.concat(b));return a},getImageUrl:function(a,d,b,c){var f=a.spatialReference.wkid||n.toJson(a.spatialReference.toJson());delete this._params._ts;var g=this._url.path+"/exportImage?";e.mixin(this._params,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:f,bboxSR:f,size:d+","+b},this.disableClientCaching?
{_ts:(new Date).getTime()}:{});var q=this._params.token=this._getToken();a=F.addProxy(g+h.objectToQuery(e.mixin(this._params,{f:"image"})));a.length>G.defaults.io.postLength||this.useMapImage?this._jsonRequest=u({url:g,content:e.mixin(this._params,{f:"json"}),callbackParamName:"callback",load:function(a,b){var d=a.href;q&&(d+=-1===d.indexOf("?")?"?token\x3d"+q:"\x26token\x3d"+q);c(F.addProxy(d))},error:this._errorHandler}):c(a)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(a,
d){this.interpolation=this._params.interpolation=a;d||this.refresh(!0)},setCompressionQuality:function(a,d){this.compressionQuality=this._params.compressionQuality=a;d||this.refresh(!0)},setBandIds:function(a,d){var b=!1;this.bandIds!==a&&(b=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(b&&!d)this.onRenderingChange();d||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=
a},setMosaicRule:function(a,d){var b=!1;this.mosaicRule!==a&&(b=!0);this.mosaicRule=a;this._params.mosaicRule=n.toJson(a.toJson());if(b&&!d)this.onMosaicRuleChange();d||this.refresh(!0)},setRenderingRule:function(a,d){var b=!1;this.renderingRule!==a&&(b=!0);this.renderingRule=a;this._params.renderingRule=a?n.toJson(a.toJson()):null;if(b&&!d)this.onRenderingChange();d||this.refresh(!0)},setImageFormat:function(a,d){this.format=this._params.format=a;d||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=
a},setDefinitionExpression:function(a,d){var b=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?b=this.defaultMosaicRule.toJson():b.method=E.METHOD_NONE);b.where=a;b=new E(b);this.setMosaicRule(b,d);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},refresh:function(a){if(a)this.inherited(arguments);else{var d=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=
d}},exportMapImage:function(a,d){var b=G.defaults.map,b=e.mixin({size:b.width+","+b.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete b._ts;this._exportMapImage(this._url.path+"/exportImage",b,d)},queryVisibleRasters:function(a,d,b,c){var e=this._map,f=r._fixDfd(new g(r._dfdCanceller));this._visibleRasters=[];var q,h,k=!0,m;if(this.infoTemplate&&this.infoTemplate.info.fieldInfos&&0<this.infoTemplate.info.fieldInfos.length){k=!1;m=this.infoTemplate.info;for(q=0;q<m.fieldInfos.length;q++)if((h=
m.fieldInfos[q])&&"raster.servicepixelvalue"!==h.fieldName.toLowerCase()&&(h.visible||m.title&&-1<m.title.toLowerCase().indexOf(h.fieldName.toLowerCase()))){k=!0;break}}q=new O;q.geometry=a.geometry;q.returnGeometry=this._map.spatialReference.equals(this.spatialReference);q.returnCatalogItems=k;q.timeExtent=a.timeExtent;q.mosaicRule=this.mosaicRule?this.mosaicRule:null;q.renderingRule=this.renderingRule?this.renderingRule:null;e&&(a=new I((e.extent.xmax-e.extent.xmin)/(2*e.width),(e.extent.ymax-e.extent.ymin)/
(2*e.height),e.extent.spatialReference),q.pixelSize=a);var l=this;a=new N(this.url);(f._pendingDfd=a.execute(q)).addCallbacks(function(a){l._queryVisibleRastersHandler(a,d,b,c,f)},function(a){l._resolve([a],null,c,f,!0)});return f},_queryVisibleRastersHandler:function(a,d,b,c,f){function h(){var a=this.getCustomRasterFields(d),c=this._getDomainFields(a),m=d?d.returnDomainValues:!1,p=d&&d.rasterAttributeTableFieldPrefix,n,r,H,v,y,u,x,w;this._getRasterAttributeTableFeatures().then(e.hitch(this,function(a){for(n=
0;n<s.length;n++){t=s[n];t.setInfoTemplate(this.infoTemplate);t._layer=this;if(g&&(r=g,l&&l.length>=n&&(H=l[n],r=H.replace(/ /gi,", ")),t.attributes["Raster.ItemPixelValue"]=r,t.attributes["Raster.ServicePixelValue"]=g,a&&0<a.length&&(v=k.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?a.attributes.Value==r:a.attributes.VALUE==r}),0<v.length&&(y=e.clone(v[0]),p&&y)))){w={};for(u in y.attributes)y.attributes.hasOwnProperty(u)&&(x=p+u,w[x]=y.attributes[u]);y.attributes=
w;t.attributes=e.mixin(t.attributes,y.attributes)}m&&(c&&0<c.length)&&k.forEach(c,function(a){if(a){var b=t.attributes[a.name];C.isDefined(b)&&(b=this._getDomainValue(a.domain,b),C.isDefined(b)&&(t.attributes[a.name]=b))}},this);z.push(t);this._visibleRasters.push(t)}this._resolve([z,null,!0],null,b,f)}))}var g=a.value,l,s,m=0,p=0,r=this,x=this.objectIdField,w;if(a.catalogItems){c=0;var A,B,v=a.catalogItems.features.length;A=0;s=Array(v);l=Array(v);w=Array(v);for(m=0;m<v;m++)-1<a.properties.Values[m].toLowerCase().indexOf("nodata")&&
A++;A=v-A;for(m=0;m<v;m++)B=-1<a.properties.Values[m].toLowerCase().indexOf("nodata")?A++:c++,s[B]=a.catalogItems.features[m],l[B]=a.properties.Values[m],w[B]=s[B].attributes[x]}this._visibleRasters=[];var t;a=-1<g.toLowerCase().indexOf("nodata");g&&(!s&&!a)&&(x="ObjectId",s=[],t=new M(new D(this.fullExtent),null,{ObjectId:0}),s.push(t));var z=[];s?!this._map.spatialReference.equals(this.spatialReference)&&w&&0<w.length?u({url:this._url.path+"/query",content:{f:"json",objectIds:w.join(","),returnGeometry:!0,
outSR:n.toJson(r._map.spatialReference.toJson()),outFields:x},handleAs:"json",callbackParamName:"callback",load:function(a){if(0===a.features.length)r._resolve([z,null,null],null,b,f);else{for(m=0;m<a.features.length;m++)for(p=0;p<s.length;p++)s[p].attributes[x]==a.features[m].attributes[x]&&(s[p].geometry=new P(a.features[m].geometry),s[p].geometry.setSpatialReference(r._map.spatialReference));h.call(r)}},error:function(a){r._resolve([z,null,null],null,b,f)}}):h.call(this):this._resolve([z,null,
null],null,b,f)},getVisibleRasters:function(){var a=this._visibleRasters,d=[],b;for(b in a)a.hasOwnProperty(b)&&d.push(a[b]);return d},_getDomainFields:function(a){if(a){var d=[];k.forEach(a,function(a){if(a.domain){var c={};c.name=a.name;c.domain=a.domain;d.push(c)}});return d}},_getDomainValue:function(a,c){if(a&&a.codedValues){var b;k.some(a.codedValues,function(a){return a.code===c?(b=a.name,!0):!1});return b}},_resolve:function(a,c,b,e,f){c&&this[c].apply(this,a);b&&b.apply(null,a);e&&r._resDfd(e,
a,f)}});c("extend-esri")&&e.setObject("layers.ArcGISImageServiceLayer",f,p);return f});