// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/data/util/filter":function(){define(["../../_base/lang"],function(l){var b={};l.setObject("dojo.data.util.filter",b);b.patternToRegExp=function(b,l){for(var g="^",d=null,a=0;a<b.length;a++)switch(d=b.charAt(a),d){case "\\":g+=d;a++;g+=b.charAt(a);break;case "*":g+=".*";break;case "?":g+=".";break;case "$":case "^":case "/":case "+":case ".":case "|":case "(":case ")":case "{":case "}":case "[":case "]":g+="\\";default:g+=d}g+="$";return l?RegExp(g,"mi"):RegExp(g,"m")};return b})},
"dojo/data/util/simpleFetch":function(){define(["../../_base/lang","../../_base/kernel","./sorter"],function(l,b,q){var n={};l.setObject("dojo.data.util.simpleFetch",n);n.errorHandler=function(g,d){d.onError&&d.onError.call(d.scope||b.global,g,d)};n.fetchHandler=function(g,d){var a=d.abort||null,f=!1,k=d.start?d.start:0,c=d.count&&Infinity!==d.count?k+d.count:g.length;d.abort=function(){f=!0;a&&a.call(d)};var e=d.scope||b.global;d.store||(d.store=this);d.onBegin&&d.onBegin.call(e,g.length,d);d.sort&&
g.sort(q.createSortFunction(d.sort,this));if(d.onItem)for(var h=k;h<g.length&&h<c;++h){var m=g[h];f||d.onItem.call(e,m,d)}d.onComplete&&!f&&(h=null,d.onItem||(h=g.slice(k,c)),d.onComplete.call(e,h,d))};n.fetch=function(b){b=b||{};b.store||(b.store=this);this._fetchItems(b,l.hitch(this,"fetchHandler"),l.hitch(this,"errorHandler"));return b};return n})},"dojo/data/util/sorter":function(){define(["../../_base/lang"],function(l){var b={};l.setObject("dojo.data.util.sorter",b);b.basicComparator=function(b,
l){var g=-1;null===b&&(b=void 0);null===l&&(l=void 0);if(b==l)g=0;else if(b>l||null==b)g=1;return g};b.createSortFunction=function(l,n){function g(a,c,b,e){return function(f,k){var h=e.getValue(f,a),d=e.getValue(k,a);return c*b(h,d)}}for(var d=[],a,f=n.comparatorMap,k=b.basicComparator,c=0;c<l.length;c++){a=l[c];var e=a.attribute;if(e){a=a.descending?-1:1;var h=k;f&&("string"!==typeof e&&"toString"in e&&(e=e.toString()),h=f[e]||k);d.push(g(e,a,h,n))}}return function(a,c){for(var b=0;b<d.length;){var e=
d[b++](a,c);if(0!==e)return e}return 0}};return b})},"esri/arcgis/csv":function(){define("dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/Geometry ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(l,b,q,n,g,d,a,f,k,c,e,h,m){function w(a){var c=0,e="";b.forEach([","," ",";","|","\t"],function(b){var f=a.split(b).length;f>c&&(c=f,e=b)});return e}function y(a,c){if(!a||
"[object Date]"!==Object.prototype.toString.call(a)||isNaN(a.getTime()))return!1;var b=!0;if(n("chrome")&&/\d+\W*$/.test(c)){var e=c.match(/[a-zA-Z]{2,}/);if(e){for(var b=!1,f=0,k=e.length,h=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!b&&f<=k&&!(b=!h.test(e[f]));)f++;b=!b}}return b}function p(a,c,e){var f=a.indexOf("\n"),f=l.trim(a.substr(0,f)),k=c.columnDelimiter;k||(k=
w(f));var h=new d({data:a,separator:k});h.fetch({onComplete:function(a,f){var k=0,t={layerDefinition:c.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},d=t.layerDefinition.objectIdField;!d&&!b.some(t.layerDefinition.fields,function(a){return"esriFieldTypeOID"==a.type?(d=a.name,!0):!1})&&(t.layerDefinition.fields.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1,domain:null}),d="__OBJECTID");var m,l,p=h._attributes,z=[],v=[];b.forEach(t.layerDefinition.fields,
function(a,c){"esriFieldTypeDate"===a.type?z.push(a.name):("esriFieldTypeDouble"===a.type||"esriFieldTypeInteger"===a.type)&&v.push(a.name)});c.locationInfo&&"coordinates"===c.locationInfo.locationType?(m=c.locationInfo.latitudeFieldName,l=c.locationInfo.longitudeFieldName):b.forEach(p,function(a){var c;c=b.indexOf(x,a.toLowerCase());-1!==c&&(m=a);c=b.indexOf(A,a.toLowerCase());-1!==c&&(l=a)},this);if(!m||!l)setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},
1),e&&e(null,Error("File does not seem to contain fields with point coordinates."));else{-1===b.indexOf(v,m)&&v.push(m);-1===b.indexOf(v,l)&&v.push(l);var p=0,w=a.length;for(p;p<w;p++){var n=a[p],q=h.getAttributes(n),r={};b.forEach(q,function(a,c){if(a){var e=a;0===a.length&&b.forEach(t.layerDefinition.fields,function(c,e){c.name==="attribute_"+(e-1)&&(a="attribute_"+(e-1))});if(-1<b.indexOf(z,a)){var e=h.getValue(n,e),f=new Date(e);r[a]=y(f,e)?f.getTime():null}else if(-1<b.indexOf(v,a)){f=g.parse(h.getValue(n,
e));if((a==m||a==l)&&(isNaN(f)||181<Math.abs(f)))f=parseFloat(h.getValue(n,e));isNaN(f)?r[a]=null:r[a]=f}else r[a]=h.getValue(n,e)}});r[d]=k;k++;var q=r[m],s=r[l];null==s||(null==q||isNaN(q)||isNaN(s))||t.featureSet.features.push({geometry:{x:s,y:q,spatialReference:{wkid:4326}},attributes:r})}t.layerDefinition.name="csv";e&&e(t)}},onError:function(a){console.error("Error fetching items from CSV store: ",a);e&&e(null,a)}});return!0}function r(a,c,e,k,d,p){0===a.length&&d(null);var g=h.getGeometryType(c),
r=[];b.forEach(a,function(a){a=new g(a);a.spatialReference=e;r.push(a)},this);c=[102113,102100,3857];e.wkid&&4326===e.wkid&&k.wkid&&-1<b.indexOf(c,k.wkid)?(b.forEach(r,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?b.forEach(a.rings,function(a){b.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?b.forEach(a.paths,function(a){b.forEach(a,
function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],b.forEach(r,function(c){c=m.geographicToWebMercator(c);102100!==k.wkid&&(c.spatialReference=k);a.push(c.toJson())},this),d(a)):null!==e.wkid&&-1<b.indexOf(c,e.wkid)&&null!==k.wkid&&4326===k.wkid?(a=[],b.forEach(r,function(c){a.push(m.webMercatorToGeographic(c).toJson())},this),d(a)):(c=function(c,
e){c&&c.length===a.length?(a=[],b.forEach(c,function(c){c&&(c.rings&&0<c.rings.length&&0<c.rings[0].length&&0<c.rings[0][0].length&&!isNaN(c.rings[0][0][0])&&!isNaN(c.rings[0][0][1])||c.paths&&0<c.paths.length&&0<c.paths[0].length&&0<c.paths[0][0].length&&!isNaN(c.paths[0][0][0])&&!isNaN(c.paths[0][0][1])||c.xmin&&!isNaN(c.xmin)&&c.ymin&&!isNaN(c.ymin)||c.x&&!isNaN(c.x)&&c.y&&!isNaN(c.y))?a.push(c.toJson()):a.push(null)},this),d(a)):p(c,e)},f.defaults.geometryService?f.defaults.geometryService.project(r,
k,l.hitch(this,c),p):d(null))}function u(a,c){var e=[102113,102100,3857];return a&&c&&a.wkid===c.wkid&&a.wkt===c.wkt||a&&c&&a.wkid&&c.wkid&&-1<b.indexOf(e,a.wkid)&&-1<b.indexOf(e,c.wkid)?!0:!1}function s(a,e,f,k){if(a.featureSet&&0!==a.featureSet.features.length)if(u(f,e))k(a);else{var d=function(c){var e=[];b.forEach(a.featureSet.features,function(a,f){c[f]&&(a.geometry=c[f],e.push(a))},this);k(a)},m=function(c,e){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");
k(a)},p=function(c,b){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Try one more time.");r(g,a.featureSet.geometryType,e,f,l.hitch(this,d),l.hitch(this,m))};if(a.featureSet.features&&0<a.featureSet.features.length){var g=[];b.forEach(a.featureSet.features,function(c){if(c.geometry.toJson)g.push(c.geometry);else{var e=h.getGeometryType(a.featureSet.geometryType);g.push(new e(c.geometry))}});e.toJson||(e=new c(e));f.toJson||(f=new c(f));r(g,a.featureSet.geometryType,e,f,l.hitch(this,
d),l.hitch(this,p))}else k(a)}}var x="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),A="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" ");e={latFieldStrings:x,longFieldStrings:A,buildCSVFeatureCollection:function(a){var c=new q,e=function(a,e){e?c.errback(e):c.callback(a)},f={url:a.url,handleAs:"text",load:function(c){p(c,a,l.hitch(this,e))},error:function(a){c.errback(a);console.error("error: "+a)}};-1<a.url.indexOf("arcgis.com")&&(-1<a.url.indexOf("/content/items")&&
-1<a.url.indexOf("/data"))&&(f.headers={"Content-Type":""});k(f,{usePost:!1});return c},projectFeatureCollection:function(a,e,f){var b=new q;f||(f=new c({wkid:4326}));s(a,f,e,l.hitch(this,function(a){b.callback(a)}));return b},generateDefaultPopupInfo:function(a){var c={esriFieldTypeDouble:1,esriFieldTypeSingle:1},e={esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},f={esriFieldTypeDate:1},k=null;a=b.map(a.layerDefinition.fields,l.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(k=a.name);
var b="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,d=null;if(b){var h=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+h+",")||-1<h.indexOf("area")||-1<h.indexOf("length")||-1<h.indexOf("shape")||-1<h.indexOf("perimeter")||-1<h.indexOf("objectid")||h.indexOf("_")===h.length-1||h.indexOf("_i")===h.length-2&&1<h.length)b=!1;a.type in e?d={places:0,digitSeparator:!0}:a.type in
c?d={places:2,digitSeparator:!0}:a.type in f&&(d={dateFormat:"shortDateShortTime"})}return l.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:b,format:d,stringFieldOption:"textbox"})}));return{title:k?"{"+k+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:w,_isValidDate:y,_processCsvData:p,_projectGeometries:r,_sameSpatialReference:u,_projectFeatureSet:s};n("extend-esri")&&l.setObject("arcgis.csv",e,a);return e})},"dojox/data/CsvStore":function(){define("dojo/_base/lang dojo/_base/declare dojo/_base/xhr dojo/_base/kernel dojo/data/util/filter dojo/data/util/simpleFetch".split(" "),
function(l,b,q,n,g,d){b=b("dojox.data.CsvStore",null,{constructor:function(a){this._attributes=[];this._attributeIndexes={};this._dataArray=[];this._arrayOfAllItems=[];this._loadFinished=!1;a.url&&(this.url=a.url);this._csvData=a.data;a.label?this.label=a.label:""===this.label&&(this.label=void 0);this._storeProp="_csvStore";this._idProp="_csvId";this._features={"dojo.data.api.Read":!0,"dojo.data.api.Identity":!0};this._loadInProgress=!1;this._queuedFetches=[];this.identifier=a.identifier;""===this.identifier?
delete this.identifier:this._idMap={};"separator"in a&&(this.separator=a.separator);"urlPreventCache"in a&&(this.urlPreventCache=a.urlPreventCache?!0:!1)},url:"",label:"",identifier:"",separator:",",urlPreventCache:!1,_assertIsItem:function(a){if(!this.isItem(a))throw Error(this.declaredClass+": a function was passed an item argument that was not an item");},_getIndex:function(a){a=this.getIdentity(a);this.identifier&&(a=this._idMap[a]);return a},getValue:function(a,f,b){this._assertIsItem(a);var c=
b;if("string"===typeof f)f=this._attributeIndexes[f],null!=f&&(c=this._dataArray[this._getIndex(a)][f]||b);else throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");return c},getValues:function(a,f){var b=this.getValue(a,f);return b?[b]:[]},getAttributes:function(a){this._assertIsItem(a);var f=[];a=this._dataArray[this._getIndex(a)];for(var b=0;b<a.length;b++)""!==a[b]&&f.push(this._attributes[b]);return f},hasAttribute:function(a,f){this._assertIsItem(a);
if("string"===typeof f){var b=this._attributeIndexes[f],c=this._dataArray[this._getIndex(a)];return"undefined"!==typeof b&&b<c.length&&""!==c[b]}throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");},containsValue:function(a,f,b){var c=void 0;"string"===typeof b&&(c=g.patternToRegExp(b,!1));return this._containsValue(a,f,b,c)},_containsValue:function(a,b,k,c){a=this.getValues(a,b);for(b=0;b<a.length;++b){var e=a[b];if("string"===typeof e&&c)return null!==
e.match(c);if(k===e)return!0}return!1},isItem:function(a){if(a&&a[this._storeProp]===this)if(a=a[this._idProp],this.identifier){if(this._dataArray[this._idMap[a]])return!0}else if(0<=a&&a<this._dataArray.length)return!0;return!1},isItemLoaded:function(a){return this.isItem(a)},loadItem:function(a){},getFeatures:function(){return this._features},getLabel:function(a){if(this.label&&this.isItem(a))return this.getValue(a,this.label)},getLabelAttributes:function(a){return this.label?[this.label]:null},
_fetchItems:function(a,b,k){var c=this,e=function(a,e){var h=null;if(a.query){var d,k,h=[],m=a.queryOptions?a.queryOptions.ignoreCase:!1,l={};for(d in a.query)k=a.query[d],"string"===typeof k&&(l[d]=g.patternToRegExp(k,m));for(m=0;m<e.length;++m){var n=!0,q=e[m];for(d in a.query)k=a.query[d],c._containsValue(q,d,k,l[d])||(n=!1);n&&h.push(q)}}else h=e.slice(0,e.length);b(h,a)};if(this._loadFinished)e(a,this._arrayOfAllItems);else if(""!==this.url)if(this._loadInProgress)this._queuedFetches.push({args:a,
filter:e});else{this._loadInProgress=!0;var h=q.get({url:c.url,handleAs:"text",preventCache:c.urlPreventCache});h.addCallback(function(b){try{c._processData(b),e(a,c._arrayOfAllItems),c._handleQueuedFetches()}catch(f){k(f,a)}});h.addErrback(function(e){c._loadInProgress=!1;if(k)k(e,a);else throw e;});var d=null;a.abort&&(d=a.abort);a.abort=function(){h&&-1===h.fired&&h.cancel();d&&d.call(a)}}else if(this._csvData)try{this._processData(this._csvData),this._csvData=null,e(a,this._arrayOfAllItems)}catch(l){k(l,
a)}else{var n=Error(this.declaredClass+": No CSV source data was provided as either URL or String data input.");if(k)k(n,a);else throw n;}},close:function(a){},_getArrayOfArraysFromCsvFileContents:function(a){if(l.isString(a)){var b=RegExp("^\\s+","g"),d=RegExp("\\s+$","g"),c=RegExp('""',"g"),e=[],h=this._splitLines(a);for(a=0;a<h.length;++a){var m=h[a];if(0<m.length){for(var m=m.split(this.separator),g=0;g<m.length;){var n=m[g].replace(b,""),p=n.replace(d,""),q=p.charAt(0),u=p.charAt(p.length-1),
s=p.charAt(p.length-2),x=p.charAt(p.length-3);if(2===p.length&&'""'==p)m[g]="";else if('"'==q&&('"'!=u||'"'==u&&'"'==s&&'"'!=x)){if(g+1===m.length)return;m[g]=n+this.separator+m[g+1];m.splice(g+1,1)}else'"'==q&&'"'==u&&(p=p.slice(1,p.length-1),p=p.replace(c,'"')),m[g]=p,g+=1}e.push(m)}}this._attributes=e.shift();for(a=0;a<this._attributes.length;a++)this._attributeIndexes[this._attributes[a]]=a;this._dataArray=e}},_splitLines:function(a){var b=[],d,c="",e=!1;for(d=0;d<a.length;d++){var h=a.charAt(d);
switch(h){case '"':e=!e;c+=h;break;case "\r":e?c+=h:(b.push(c),c="",d<a.length-1&&"\n"==a.charAt(d+1)&&d++);break;case "\n":e?c+=h:(b.push(c),c="");break;default:c+=h}}""!==c&&b.push(c);return b},_processData:function(a){this._getArrayOfArraysFromCsvFileContents(a);this._arrayOfAllItems=[];if(this.identifier&&void 0===this._attributeIndexes[this.identifier])throw Error(this.declaredClass+": Identity specified is not a column header in the data set.");for(a=0;a<this._dataArray.length;a++){var b=a;
this.identifier&&(b=this._dataArray[a][this._attributeIndexes[this.identifier]],this._idMap[b]=a);this._arrayOfAllItems.push(this._createItemFromIdentity(b))}this._loadFinished=!0;this._loadInProgress=!1},_createItemFromIdentity:function(a){var b={};b[this._storeProp]=this;b[this._idProp]=a;return b},getIdentity:function(a){return this.isItem(a)?a[this._idProp]:null},fetchItemByIdentity:function(a){var b,d=a.scope?a.scope:n.global;if(this._loadFinished)b=this._createItemFromIdentity(a.identity),this.isItem(b)||
(b=null),a.onItem&&a.onItem.call(d,b);else{var c=this;if(""!==this.url)this._loadInProgress?this._queuedFetches.push({args:a}):(this._loadInProgress=!0,b=q.get({url:c.url,handleAs:"text"}),b.addCallback(function(b){try{c._processData(b);var e=c._createItemFromIdentity(a.identity);c.isItem(e)||(e=null);a.onItem&&a.onItem.call(d,e);c._handleQueuedFetches()}catch(f){a.onError&&a.onError.call(d,f)}}),b.addErrback(function(c){this._loadInProgress=!1;a.onError&&a.onError.call(d,c)}));else if(this._csvData)try{c._processData(c._csvData),
c._csvData=null,b=c._createItemFromIdentity(a.identity),c.isItem(b)||(b=null),a.onItem&&a.onItem.call(d,b)}catch(e){a.onError&&a.onError.call(d,e)}}},getIdentityAttributes:function(a){return this.identifier?[this.identifier]:null},_handleQueuedFetches:function(){if(0<this._queuedFetches.length){for(var a=0;a<this._queuedFetches.length;a++){var b=this._queuedFetches[a],d=b.filter,c=b.args;d?d(c,this._arrayOfAllItems):this.fetchItemByIdentity(b.args)}this._queuedFetches=[]}}});l.extend(b,d);return b})},
"*noref":1}});
define("esri/layers/CSVLayer","dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../arcgis/csv ./FeatureLayer ../geometry/Extent ../tasks/FeatureSet".split(" "),function(l,b,q,n,g,d,a,f,k){b=b(a,{declaredClass:"esri.layers.CSVLayer",_preventInit:!0,_fieldTypeMap:{Date:"esriFieldTypeDate",Number:"esriFieldTypeDouble",String:"esriFieldTypeString"},constructor:function(a,b){this.url=a;b=q.mixin(b,{outFields:["*"]});this.columnDelimiter=b.columnDelimiter;this.latitudeFieldName=b.latitudeFieldName;
this.longitudeFieldName=b.longitudeFieldName;var d=b.layerDefinition;d||(d={fields:b.fields||[],geometryType:"esriGeometryPoint",copyrightText:b.copyright},b.fields&&l.forEach(b.fields,q.hitch(this,function(a){a.type=this._fieldTypeMap[a.type||"String"];a.alias||(a.alias=a.name)})));this._buildCsvFcParam={url:this.url,columnDelimiter:this.columnDelimiter,layerDefinition:d};this.latitudeFieldName&&this.longitudeFieldName&&(this._buildCsvFcParam.locationInfo={locationType:"coordinates",latitudeFieldName:this.latitudeFieldName,
longitudeFieldName:this.longitudeFieldName});this._projectFeatures=q.hitch(this,this._projectFeatures);this._addFeatures=q.hitch(this,this._addFeatures);this._initCSVLayer(b)},refresh:function(){this._fireUpdateStart();this.applyEdits(null,null,this.graphics);this._loadFeatures()},_setMap:function(a){var b=this.inherited(arguments);this._fireUpdateStart();this._projectFeatures(this._csvFC).then(this._addFeatures).otherwise(this._errorHandler);this._csvFC=null;return b},_initCSVLayer:function(a){var b=
this;d.buildCSVFeatureCollection(this._buildCsvFcParam).then(function(d){b._csvFC=d;var f=d.layerDefinition;f.extent=b._getFCExtent(d);b._initFeatureLayer({layerDefinition:f},a)}).otherwise(this._errorHandler)},_loadFeatures:function(){d.buildCSVFeatureCollection(this._buildCsvFcParam).then(this._projectFeatures).then(this._addFeatures).otherwise(this._errorHandler)},_projectFeatures:function(a){return d.projectFeatureCollection(a,this._map.spatialReference)},_addFeatures:function(a){a=new k(a.featureSet);
this.applyEdits(a.features,null,null);this._fireUpdateEnd()},_getFCExtent:function(a){var b;if(a&&a.featureSet&&a.featureSet.features){a=a.featureSet.features;var d=a.length;if(1<d){var g=a[0].geometry;b=new f(g.x,g.y,g.x,g.y);for(d-=1;0<d;d--)g=a[d].geometry,b.xmin=Math.min(b.xmin,g.x),b.ymin=Math.min(b.ymin,g.y),b.xmax=Math.max(b.xmax,g.x),b.ymax=Math.max(b.ymax,g.y);0>=b.getWidth()&&0>=b.getHeight()&&(b=null)}}return b}});n("extend-esri")&&q.setObject("layers.CSVLayer",b,g);return b});