// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.11/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/KMLGroundOverlay":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../lang ./MapImage".split(" "),function(l,m,k,h,e,p){l=l([p],{declaredClass:"esri.layers.KMLGroundOverlay",constructor:function(h){e.isDefined(this.visibility)&&(this.visible=!!this.visibility)}});k("extend-esri")&&m.setObject("layers.KMLGroundOverlay",l,h);return l})},"esri/layers/KMLFolder":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],
function(l,m,k,h,e){l=l(null,{declaredClass:"esri.layers.KMLFolder",constructor:function(h){m.mixin(this,h);e.isDefined(this.visibility)&&(this.visible=!!this.visibility)}});k("extend-esri")&&m.setObject("layers.KMLFolder",l,h);return l})},"*noref":1}});
define("esri/layers/KMLLayer","dojo/_base/kernel dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/_base/json dojo/_base/sniff dojo/io-query dojo/dom-construct dojo/dom-style ../kernel ../config ../lang ../request ../SpatialReference ../geometry/webMercatorUtils ../dijit/PopupTemplate ./layer ./KMLFolder ./KMLGroundOverlay ./MapImageLayer ./FeatureLayer".split(" "),function(l,m,k,h,e,p,w,t,u,x,q,v,y,z,A,r,B,C,D,E,F,G){var s=m([C],{declaredClass:"esri.layers.KMLLayer",serviceUrl:location.protocol+
"//utility.arcgis.com/sharing/kml",constructor:function(a,b){a||console.log("KMLLayer:constructor - please provide url for the KML file");this._outSR=b&&b.outSR||new A({wkid:4326});this._options=h.mixin({},b);v.defaults.kmlService&&(this.serviceUrl=v.defaults.kmlService);var c=this.linkInfo=b&&b.linkInfo;c&&(this.visible=!!c.visibility,this._waitingForMap=!!c.viewFormat);(!c||c&&c.visibility&&!this._waitingForMap)&&this._parseKml();this.refresh=h.hitch(this,this.refresh);this.registerConnectEvents("esri.layers.KMLLayer",
!0)},getFeature:function(a){if(a){var b=a.type,c=a.id,d;switch(b){case "esriGeometryPoint":case "esriGeometryPolyline":case "esriGeometryPolygon":(a=this["_"+b])&&(d=h.getObject("_mode._featureMap."+c,!1,a));break;case "GroundOverlay":if(a=this._groundLyr){var f=a.getImages(),b=f.length;for(a=0;a<b;a++)if(f[a].id===c){d=f[a];break}}break;case "ScreenOverlay":break;case "NetworkLink":e.some(this._links,function(a){return a.linkInfo&&a.linkInfo.id===c?(d=a,!0):!1});break;case "Folder":b=(f=this.folders)?
f.length:0;for(a=0;a<b;a++)if(f[a].id===c){d=f[a];break}break;default:console.log("KMLLayer:getFeature - unknown feature type")}return d}},getLayers:function(){var a=[];this._groundLyr&&a.push(this._groundLyr);this._fLayers&&(a=a.concat(this._fLayers));this._links&&e.forEach(this._links,function(b){b.declaredClass&&a.push(b)});return a},setFolderVisibility:function(a,b){a&&(this._fireUpdateStart(),(a.visible=b)&&(b=this._areLocalAncestorsVisible(a)),this._setState(a,b),this._fireUpdateEnd())},onRefresh:function(){},
onOpacityChange:function(){},_parseKml:function(a){var b=this;this._fireUpdateStart();this._io=z({url:this.serviceUrl,content:{url:this._url.path+this._getQueryParameters(a),model:"simple",folders:"",refresh:this.loaded?!0:void 0,outSR:p.toJson(this._outSR.toJson())},callbackParamName:"callback",load:function(a){b._io=null;b._initLayer(a)},error:function(a){b._io=null;a=h.mixin(Error(),a);a.message="Unable to load KML: "+b.url+" "+(a.message||"");b._fireUpdateEnd(a);b.onError(a)}})},_initLayer:function(a){this.loaded&&
this._removeInternalLayers();this.name=a.name;this.description=a.description;this.snippet=a.snippet;this.visibility=a.visibility;this.featureInfos=a.featureInfos;var b,c,d=this.folders=a.folders,f=[],n;if(d){c=d.length;for(b=0;b<c;b++)n=d[b]=new D(d[b]),-1===n.parentFolderId&&f.push(n)}var d=this._links=a.networkLinks,g;c=d?d.length:0;for(b=0;b<c;b++)d[b].viewRefreshMode&&-1!==d[b].viewRefreshMode.toLowerCase().indexOf("onregion")||(g=h.mixin({},this._options),g.linkInfo=d[b],g.id&&(g.id=g.id+"_"+
b),d[b]=new s(d[b].href,g),d[b]._parentLayer=this,d[b]._parentFolderId=this._getLinkParentId(d[b].linkInfo.id));if((d=a.groundOverlays)&&0<d.length){g=h.mixin({},this._options);g.id&&(g.id+="_mapImage");n=this._groundLyr=new F(g);c=d.length;for(b=0;b<c;b++)n.addImage(new E(d[b]))}if((a=h.getObject("featureCollection.layers",!1,a))&&0<a.length)this._fLayers=[],e.forEach(a,function(a,b){var c=h.getObject("featureSet.features",!1,a);c&&0<c.length&&(g=h.mixin({outFields:["*"],infoTemplate:a.popupInfo?
new B(a.popupInfo):null,editable:!1},this._options),g.id&&(g.id=g.id+"_"+b),a.layerDefinition.capabilities="Query,Data",c=new G(a,g),c.geometryType&&(this["_"+c.geometryType]=c),this._fLayers.push(c))},this),0===this._fLayers.length&&delete this._fLayers;c=f.length;for(b=0;b<c;b++)n=f[b],this._setState(n,n.visible);this._fireUpdateEnd();this.loaded?(this._addInternalLayers(),this.onRefresh()):(this.loaded=!0,this.onLoad(this))},_addInternalLayers:function(){var a=this._map;this._fireUpdateStart();
this._links&&e.forEach(this._links,function(b){b.declaredClass&&(a.addLayer(b),b._waitingForMap&&(b._waitingForMap=null,b.visible?b._parseKml(a):b._wMap=a))});var b=a.spatialReference,c=this._outSR,d;if(!b.equals(c))if(b.isWebMercator()&&4326===c.wkid)d=r.geographicToWebMercator;else if(c.isWebMercator()&&4326===b.wkid)d=r.webMercatorToGeographic;else{console.log("KMLLayer:_setMap - unsupported workflow. Spatial reference of the map and kml layer do not match, and the conversion cannot be done on the client.");
return}this._groundLyr&&(d&&e.forEach(this._groundLyr.getImages(),function(a){a.extent=d(a.extent)}),a.addLayer(this._groundLyr));(b=this._fLayers)&&0<b.length&&e.forEach(b,function(b){if(d){var c=b.graphics,g,e,h=c?c.length:0;for(g=0;g<h;g++)(e=c[g].geometry)&&c[g].setGeometry(d(e))}a.addLayer(b)});this.onVisibilityChange(this.visible)},_removeInternalLayers:function(){var a=this._map;this._links&&e.forEach(this._links,function(a){a.declaredClass&&a._io&&a._io.cancel()});a&&e.forEach(this.getLayers(),
a.removeLayer,a)},_setState:function(a,b){var c=a.featureInfos,d,f,e,g=c?c.length:0,h=b?"show":"hide";for(e=0;e<g;e++)if(d=c[e],f=this.getFeature(d))if("Folder"===d.type)this._setState(f,b&&f.visible);else if("NetworkLink"===d.type)this._setInternalVisibility(f,b);else f[h]()},_areLocalAncestorsVisible:function(a){var b=a.parentFolderId;for(a=a.visible;a&&-1!==b;)b=this.getFeature({type:"Folder",id:b}),a=a&&b.visible,b=b.parentFolderId;return a},_setInternalVisibility:function(a,b){var c=a._parentLayer,
d=a._parentFolderId;for(b=b&&a.visible;b&&c;)b=b&&c.visible,-1<d&&(b=b&&c._areLocalAncestorsVisible(c.getFeature({type:"Folder",id:d}))),d=c._parentFolderId,c=c._parentLayer;this._setIntState(a,b)},_setIntState:function(a,b){a&&e.forEach(a.getLayers(),function(c){c.linkInfo?a._setIntState(c,b&&c.visible&&a._areLocalAncestorsVisible(a.getFeature({type:"Folder",id:c._parentFolderId}))):c.setVisibility(b)})},_getLinkParentId:function(a){var b=-1;this.folders&&e.some(this.folders,function(c){return c.networkLinkIds&&
-1!==e.indexOf(c.networkLinkIds,a)?(b=c.id,!0):!1});return b},_checkAutoRefresh:function(){var a=this.linkInfo;if(a)if(this.visible){if(this.loaded&&this._map){var b=a.refreshMode,c=a.refreshInterval,d=a.viewRefreshMode,a=a.viewRefreshTime;b&&(-1!==b.toLowerCase().indexOf("oninterval")&&0<c)&&(this._stopAutoRefresh(),this._timeoutHandle=setTimeout(this.refresh,1E3*c));d&&(-1!==d.toLowerCase().indexOf("onstop")&&0<a)&&!this._extChgHandle&&(this._extChgHandle=k.connect(this._map,"onExtentChange",this,
this._extentChanged))}}else this._stopAutoRefresh(),k.disconnect(this._extChgHandle),delete this._extChgHandle},_stopAutoRefresh:function(){clearTimeout(this._timeoutHandle);this._timeoutHandle=null},_getQueryParameters:function(a){a=a||this._map;var b={},c=this.linkInfo,d=a&&a.extent,f;this._url.query&&(h.mixin(b,this._url.query),f=!!this._url.query.token);if(q.id&&!f&&(f=q.id.findCredential(this._url.path)))b.token=f.token;if(c){f=c.viewFormat;var e=c.httpQuery,c=c.viewBoundScale;if(d&&f){var g=
d,k=d,m=d.spatialReference;m&&(m.isWebMercator()?g=r.webMercatorToGeographic(d):4326===m.wkid&&(k=r.geographicToWebMercator(d)));d=g.getCenter();k=Math.max(k.getWidth(),k.getHeight());c&&(g=g.expand(c));f=f.replace(/\[bboxWest\]/ig,g.xmin).replace(/\[bboxEast\]/ig,g.xmax).replace(/\[bboxSouth\]/ig,g.ymin).replace(/\[bboxNorth\]/ig,g.ymax).replace(/\[lookatLon\]/ig,d.x).replace(/\[lookatLat\]/ig,d.y).replace(/\[lookatRange\]/ig,k).replace(/\[lookatTilt\]/ig,0).replace(/\[lookatHeading\]/ig,0).replace(/\[lookatTerrainLon\]/ig,
d.x).replace(/\[lookatTerrainLat\]/ig,d.y).replace(/\[lookatTerrainAlt\]/ig,0).replace(/\[cameraLon\]/ig,d.x).replace(/\[cameraLat\]/ig,d.y).replace(/\[cameraAlt\]/ig,k).replace(/\[horizFov\]/ig,60).replace(/\[vertFov\]/ig,60).replace(/\[horizPixels\]/ig,a.width).replace(/\[vertPixels\]/ig,a.height).replace(/\[terrainEnabled\]/ig,0);h.mixin(b,t.queryToObject(f))}e&&(e=e.replace(/\[clientVersion\]/ig,q.version).replace(/\[kmlVersion\]/ig,2.2).replace(/\[clientName\]/ig,"ArcGIS API for JavaScript").replace(/\[language\]/ig,
l.locale),h.mixin(b,t.queryToObject(e)))}a=[];for(var p in b)y.isDefined(b[p])&&a.push(p+"\x3d"+b[p]);return(a=a.join("\x26"))?"?"+a:""},setScaleRange:function(a,b){this.inherited(arguments);e.forEach(this.getLayers(),function(c){c.setScaleRange(a,b)});this._options.minScale=this.minScale;this._options.maxScale=this.maxScale},setOpacity:function(a){this.opacity!=a&&(e.forEach(this.getLayers(),function(b){b.setOpacity(a)}),this.opacity=this._options.opacity=a,this.onOpacityChange(a))},_setMap:function(a,
b){this.inherited(arguments);this._map=a;var c=this._div=u.create("div",null,b);x.set(c,"position","absolute");this._addInternalLayers();this.evaluateSuspension();return c},_unsetMap:function(a,b){this._io&&this._io.cancel();this._stopAutoRefresh();k.disconnect(this._extChgHandle);delete this._extChgHandle;this._removeInternalLayers();var c=this._div;c&&(b.removeChild(c),u.destroy(c));this._wMap=this._div=null;this.inherited(arguments)},onVisibilityChange:function(a){this.loaded?(this._fireUpdateStart(),
this._setInternalVisibility(this,a),this._checkAutoRefresh(),this._fireUpdateEnd()):this.linkInfo&&a&&(this._waitingForMap||this._parseKml(this._wMap))},refresh:function(){this.loaded&&(this._map&&!this._io&&this.visible)&&this._parseKml()},getFeatureCollection:function(a){var b,c=[];if(a=this.getFeature({type:"Folder",id:a}))(b=e.map(a.featureInfos,function(a){if("esriGeometryPoint"===a.type||"esriGeometryPolyline"===a.type||"esriGeometryPolygon"===a.type)return a.id},this))&&0<b.length&&e.forEach(this._fLayers,
function(a){var f,h;f=a.toJson();f.featureSet.features&&0<f.featureSet.features.length&&(h=e.filter(f.featureSet.features,function(c){if(-1!==e.indexOf(b,c.attributes[a.objectIdField]))return c},this));h&&0<h.length&&(f.featureSet.features=h,c.push(f))},this);return c},getFeatureCount:function(a){a=this.getFeature({type:"Folder",id:a});var b={points:0,polylines:0,polygons:0};a&&e.forEach(a.featureInfos,function(a){"esriGeometryPoint"===a.type&&(b.points+=1);"esriGeometryPolyline"===a.type&&(b.polylines+=
1);"esriGeometryPolygon"===a.type&&(b.polygons+=1)});return b},_extentChanged:function(){this._stopAutoRefresh();this._timeoutHandle=setTimeout(this.refresh,1E3*this.linkInfo.viewRefreshTime)}});w("extend-esri")&&h.setObject("layers.KMLLayer",s,q);return s});